In [1]:
import torch
import numpy as np

def sigmoid(z):
   return 1 / (1 + np.exp(-z))

In [73]:
#m = input("Please enter an integer: ")

x = torch.rand(3, 784)

w = torch.rand(784, 10)

b = torch.rand((1, 10))

y_true = torch.tensor([[1,    #0
                        0,    #1
                        0,    #2
                        0,    #3
                        0,    #4
                        0,    #5
                        0,    #6
                        0,    #7
                        0,    #8
                        0,]]) #9

In [71]:
def train_perceptron(x, w, b, y_true, mu):

  #For every photo of 28X28
  for p, _ in enumerate(x):

    print(p)

    photo = x[p]
    ##Forward##
    z = torch.mm(photo.unsqueeze(0),w)
    z = z + b

    #Activation
    y_aprox = z.clone()  # Clone the original tensor to avoid modifying it in-place
    y_aprox.apply_(lambda x: sigmoid(x))

    #Loss
    Error = y_true - y_aprox

    ##Back##
    #For every perceptron
    for i in range(10):
      b[0][i] = b[0][i] + mu * Error[0][i]
      #For every weight
      for j in range(784):
        w[j][i] = w[j][i] + mu * x[p][j] * Error[0][i]

    print("Weights on iteration ", p)
    print(w)
    print("Biases on iteration ", p)
    print(b)
    print()

  print("Final Values")
  return w, b

In [74]:
train_perceptron(x, w, b, y_true, 0.5)

0
Weights on iteration  0
tensor([[ 0.7222,  0.5424, -0.0130,  ...,  0.2928,  0.3359,  0.8251],
        [ 0.7839,  0.5096,  0.4571,  ...,  0.5978,  0.5107,  0.6101],
        [ 0.4941,  0.8584,  0.8452,  ..., -0.1253,  0.3096, -0.1038],
        ...,
        [ 0.6583,  0.7669,  0.4340,  ...,  0.2215,  0.8747,  0.4457],
        [ 0.4016, -0.3864, -0.4305,  ..., -0.2472, -0.4210,  0.0218],
        [ 0.2040, -0.3888, -0.2891,  ...,  0.0657,  0.1610, -0.3547]])
Biases on iteration  0
tensor([[ 0.0098, -0.4960, -0.0409, -0.4217, -0.1909,  0.4731,  0.1603,  0.0920,
         -0.1464, -0.2056]])

1
Weights on iteration  1
tensor([[ 0.7222,  0.0960, -0.4593,  ..., -0.1535, -0.1105,  0.3787],
        [ 0.7839,  0.3794,  0.3269,  ...,  0.4676,  0.3805,  0.4799],
        [ 0.4941,  0.6139,  0.6007,  ..., -0.3698,  0.0651, -0.3483],
        ...,
        [ 0.6583,  0.4915,  0.1586,  ..., -0.0539,  0.5993,  0.1704],
        [ 0.4016, -0.4848, -0.5290,  ..., -0.3456, -0.5194, -0.0767],
        [ 0.2040,

(tensor([[ 0.7222,  0.0158, -0.6162,  ..., -0.2295, -0.1141,  0.3536],
         [ 0.7839,  0.1857, -0.0517,  ...,  0.2843,  0.3718,  0.4192],
         [ 0.4941,  0.6107,  0.5945,  ..., -0.3728,  0.0649, -0.3493],
         ...,
         [ 0.6583,  0.3593, -0.1000,  ..., -0.1791,  0.5933,  0.1289],
         [ 0.4016, -0.6774, -0.9054,  ..., -0.5279, -0.5281, -0.1370],
         [ 0.2040, -0.7996, -0.8263,  ..., -0.3380, -0.1233, -0.6745]]),
 tensor([[ 0.0098, -1.1976, -0.9350, -0.9398, -1.1901, -0.0306, -0.6770, -0.5988,
          -0.6555, -0.7687]]))