In [37]:
import torch

In [38]:
x = torch.rand(10, 784)
w = torch.rand(784, 10)
b = torch.rand(10)

y_true = torch.rand(10, 10)
print(y_true)


def sigmoid(x):
    return 1 / (1 + torch.exp(-x))

def gradients(x, y, y_hat, z):
    print(y_hat)
    print(y)
    dL_dZ = y_hat - y
    dZ_dW = x
    dL_dW = dZ_dW.T @ dL_dZ
    dL_db = (dL_dZ).sum(dim=0)
    return dL_dW, dL_db

tensor([[0.4343, 0.1394, 0.4421, 0.0489, 0.2255, 0.5751, 0.2474, 0.7388, 0.4314,
         0.9386],
        [0.2630, 0.6496, 0.4253, 0.1837, 0.7855, 0.5259, 0.3723, 0.2858, 0.1280,
         0.4624],
        [0.0281, 0.3458, 0.0120, 0.4320, 0.3526, 0.3885, 0.3029, 0.6033, 0.2822,
         0.9920],
        [0.4945, 0.9928, 0.7642, 0.7957, 0.6974, 0.9978, 0.3792, 0.5126, 0.2703,
         0.7005],
        [0.0910, 0.5531, 0.0303, 0.0292, 0.4764, 0.1027, 0.1922, 0.3953, 0.1703,
         0.3524],
        [0.2111, 0.9357, 0.5648, 0.6215, 0.9579, 0.7979, 0.5040, 0.7855, 0.7171,
         0.2581],
        [0.7297, 0.8611, 0.4926, 0.9797, 0.2772, 0.4137, 0.5414, 0.6480, 0.1222,
         0.7763],
        [0.3279, 0.3380, 0.9286, 0.2947, 0.4013, 0.2520, 0.3685, 0.5166, 0.5804,
         0.4814],
        [0.5837, 0.4425, 0.2941, 0.1145, 0.6050, 0.9473, 0.4262, 0.1227, 0.7539,
         0.7453],
        [0.7516, 0.5116, 0.9421, 0.0919, 0.7473, 0.8735, 0.0469, 0.5614, 0.8137,
         0.6172]])


In [39]:

def train_perceptron(x, w, b, y_true, mu):
    #forward propagation
    z = x @ w + b
    y_hat = sigmoid(z)
    #print("testtest")
    print(y_hat)

    dL_dW, dL_db = gradients(x, y_true, y_hat, z)
    w = w - mu * dL_dW
    b = b - mu * dL_db
    return w, b



In [40]:
mu = 0.1
w, b = train_perceptron(x, w, b, y_true, mu)

#print(w)
#print(b)
print(w.shape)
print(b.shape)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]