In [27]:
import torch

In [28]:
x = torch.rand(10, 784)
w = torch.rand(784, 10)
b = torch.rand(10)

y_true = torch.rand(10, 10)
print(y_true)


def sigmoid(x):
    return 1 / (1 + torch.exp(-x))

def gradients(x, y, y_hat, z):
    print(y_hat)
    print(y)
    dL_dZ = y_hat - y
    dZ_dW = x
    dL_dW = dZ_dW.T @ dL_dZ
    dL_db = (dL_dZ).sum(dim=0)
    return dL_dW, dL_db

tensor([[0.4305, 0.8347, 0.9848, 0.8591, 0.3599, 0.0952, 0.2558, 0.1897, 0.2402,
         0.0110],
        [0.0656, 0.3101, 0.7007, 0.4500, 0.9488, 0.4765, 0.3208, 0.2358, 0.2557,
         0.1042],
        [0.7082, 0.7079, 0.1886, 0.6881, 0.9130, 0.2653, 0.4965, 0.9833, 0.6183,
         0.0075],
        [0.7448, 0.5058, 0.3994, 0.4239, 0.3943, 0.2059, 0.2898, 0.2645, 0.9017,
         0.7447],
        [0.5452, 0.5665, 0.9044, 0.9341, 0.8012, 0.1972, 0.3468, 0.4287, 0.6898,
         0.8268],
        [0.8784, 0.7422, 0.8668, 0.1396, 0.7369, 0.1484, 0.6834, 0.0779, 0.8735,
         0.1039],
        [0.7310, 0.6672, 0.4084, 0.0874, 0.8057, 0.4444, 0.3684, 0.1610, 0.7332,
         0.0240],
        [0.5643, 0.5960, 0.4105, 0.2598, 0.5323, 0.5972, 0.2400, 0.8239, 0.1665,
         0.0666],
        [0.7454, 0.0756, 0.4707, 0.2448, 0.1814, 0.1968, 0.2292, 0.2429, 0.2670,
         0.3721],
        [0.4518, 0.2344, 0.7711, 0.7382, 0.4684, 0.6897, 0.0903, 0.6861, 0.6306,
         0.7307]])


In [33]:

def train_perceptron(x, w, b, y_true, mu):
    #forward propagation
    z = x @ w + b
    y_hat = sigmoid(z)
    #print("testtest")
    print(y_hat)

    dL_dW, dL_db = gradients(x, y_true, y_hat, z)
    w = w - mu * dL_dW
    b = b - mu * dL_db
    return w, b



tensor([[9.2343e-01, 7.0147e-01, 6.3371e-01, 3.0137e-01, 5.1546e-01, 1.8423e-01,
         3.1885e-01, 3.4718e-01, 1.7603e-01, 2.2700e-01],
        [6.2476e-01, 9.3757e-01, 4.7032e-01, 5.1382e-01, 7.0208e-01, 2.5388e-01,
         6.6432e-01, 3.7463e-01, 7.1804e-02, 9.7026e-01],
        [2.5265e-01, 8.1372e-01, 5.5615e-01, 3.2202e-01, 2.4317e-01, 1.2670e-01,
         2.8928e-01, 5.9722e-01, 4.7929e-01, 5.6453e-01],
        [1.5534e-01, 3.9705e-01, 9.5777e-01, 6.4059e-01, 3.9039e-01, 4.6399e-01,
         8.9015e-01, 1.6478e-01, 6.2614e-01, 3.0296e-01],
        [8.1604e-01, 8.2326e-01, 4.9505e-01, 7.8660e-01, 1.7218e-01, 2.7374e-01,
         4.1170e-01, 5.4345e-01, 8.6504e-04, 7.8138e-01],
        [4.3466e-01, 5.3705e-01, 5.1981e-01, 5.5526e-01, 3.5521e-01, 6.5669e-01,
         6.9909e-01, 9.2849e-01, 1.2465e-01, 5.7395e-01],
        [5.3995e-01, 4.0075e-01, 8.8755e-01, 8.3871e-01, 7.9274e-01, 2.1279e-01,
         8.7357e-01, 6.9031e-01, 3.0210e-01, 4.1856e-01],
        [1.8769e-01, 6.4391

In [36]:
mu = 0.1
w, b = train_perceptron(x, w, b, y_true, mu)

#print(w)
#print(b)
print(w.shape)
print(b.shape)

aoleu
tensor([[1.0000e+00, 8.0952e-13, 6.0443e-29, 2.0916e-30, 1.0000e+00, 6.2696e-02,
         1.0000e+00, 1.0000e+00, 1.0000e+00, 1.2309e-15],
        [1.0000e+00, 7.9003e-07, 6.9610e-27, 3.6170e-26, 1.0000e+00, 8.9891e-01,
         1.0000e+00, 1.0000e+00, 1.0000e+00, 3.6966e-12],
        [1.0000e+00, 1.0705e-07, 1.2227e-27, 1.5233e-25, 1.0000e+00, 4.7078e-03,
         1.0000e+00, 1.0000e+00, 1.0000e+00, 3.4317e-14],
        [1.0000e+00, 1.8709e-11, 9.3972e-24, 9.6435e-23, 1.0000e+00, 9.9778e-01,
         1.0000e+00, 1.0000e+00, 1.0000e+00, 2.6951e-15],
        [1.0000e+00, 1.6240e-09, 3.9609e-27, 4.0149e-22, 1.0000e+00, 9.0099e-01,
         1.0000e+00, 1.0000e+00, 1.0000e+00, 1.5423e-12],
        [1.0000e+00, 3.3532e-11, 4.9342e-27, 2.2809e-25, 1.0000e+00, 9.9998e-01,
         1.0000e+00, 1.0000e+00, 1.0000e+00, 3.9133e-13],
        [1.0000e+00, 5.7752e-13, 6.5698e-27, 5.0138e-25, 1.0000e+00, 6.9736e-01,
         1.0000e+00, 1.0000e+00, 1.0000e+00, 7.9920e-16],
        [1.0000e+00, 