In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorboard
import random

In [2]:
m=4
x=torch.rand((m, 784))
w=torch.rand((784,10))
b=torch.rand((10,))
lr=0.1
y=torch.zeros((m,10))
for i in range(0,m):
    y[i][random.randint(0,9)]=1

print(x.shape)
print(w.shape)
print(b.shape)
print(y.shape)
print(w)
print(b)

torch.Size([4, 784])
torch.Size([784, 10])
torch.Size([10])
torch.Size([4, 10])
tensor([[0.8629, 0.6214, 0.8505,  ..., 0.0836, 0.8333, 0.3944],
        [0.9224, 0.6506, 0.8883,  ..., 0.7643, 0.4892, 0.2697],
        [0.8861, 0.8373, 0.1614,  ..., 0.0612, 0.4005, 0.3464],
        ...,
        [0.2916, 0.7280, 0.6231,  ..., 0.5194, 0.9764, 0.4795],
        [0.8067, 0.1940, 0.7967,  ..., 0.9006, 0.9351, 0.7468],
        [0.4450, 0.7360, 0.4483,  ..., 0.6785, 0.3183, 0.2910]])
tensor([0.9921, 0.0261, 0.5479, 0.2390, 0.5732, 0.6882, 0.1370, 0.3164, 0.6260,
        0.5943])


In [3]:
def sigmoid(x):
    # print(x)
    # print(torch.exp(-x))
    # print(1+torch.exp(-x))
    return 1/(1+torch.exp(-x))

In [4]:
def train_perceptron(X:torch.Tensor,W:torch.Tensor,b:torch.Tensor,y_true:torch.Tensor,lr:float):
    z=X@W+b
    y_pred=sigmoid(z)
    err=y_true-y_pred
    W_new=W+lr*x.T@err
    b_new=b+lr*err.mean(axis=0)
    return W_new,b_new

In [5]:
w,b=train_perceptron(x,w,b,y,lr)
print(w)
print(b)

tensor([[ 0.7324,  0.5174,  0.6787,  ..., -0.0462,  0.6821,  0.2226],
        [ 0.7600,  0.4499,  0.6533,  ...,  0.5677,  0.3440,  0.0348],
        [ 0.7554,  0.6804, -0.0090,  ..., -0.0161,  0.2541,  0.1760],
        ...,
        [ 0.0489,  0.5400,  0.3804,  ...,  0.3657,  0.8325,  0.2367],
        [ 0.6097,  0.0371,  0.5641,  ...,  0.7527,  0.7390,  0.5142],
        [ 0.3279,  0.5893,  0.3006,  ...,  0.6295,  0.1880,  0.1433]])
tensor([ 0.9171, -0.0489,  0.4479,  0.1390,  0.4732,  0.5882,  0.0370,  0.2414,
         0.5510,  0.4943])
