In [9]:
import torch
import torch.nn as nn

In [10]:
input_d = torch.tensor([1, 3, 0]).float()
labels = torch.tensor([0, 1, 0]).float()

#weights_from_class = torch.tensor([[0.1, 0.2, -0.3], [-0.6, -0.5, 2], [-0.2, 0.5, -3]]).float()
weights_from_assignment = torch.tensor([[0.3, 0.1, -2], [-0.6, -0.5, 2], [-1, 0.5, 0.1]]).float()
biases = torch.tensor([0.1, 0.1, 0.1]).float()

In [11]:
def feed_forward(input_arg: torch.tensor, weights_arg: torch.tensor, biases_arg: torch.tensor) -> torch.tensor:
    z = torch.matmul(weights_arg, input_arg) + biases_arg
    return nn.Softmax(dim=0)(z)

In [12]:
def compute_gradients(input_arg: torch.tensor, labels_arg: torch.tensor, predicted_arg: torch.tensor) -> (torch.tensor, torch.tensor):
    return torch.matmul(input_arg.view(-1, 1), (predicted_arg - labels_arg).view(1, -1)), predicted_arg - labels_arg

In [13]:
predicted = feed_forward(input_d, weights_from_assignment, biases)
print(predicted)

tensor([0.5071, 0.0341, 0.4588])


In [14]:
d_weights, d_biases = compute_gradients(input_d, labels, predicted)
print(d_weights)
print(d_biases)

tensor([[ 0.5071, -0.9659,  0.4588],
        [ 1.5213, -2.8978,  1.3765],
        [ 0.0000, -0.0000,  0.0000]])
tensor([ 0.5071, -0.9659,  0.4588])


In [15]:
weights = weights_from_assignment - d_weights
biases = biases - d_biases

print(weights)
print(biases)

tensor([[-0.2071,  1.0659, -2.4588],
        [-2.1213,  2.3978,  0.6235],
        [-1.0000,  0.5000,  0.1000]])
tensor([-0.4071,  1.0659, -0.3588])


In [16]:
predicted_after_train = feed_forward(input_d, weights, biases)
print(predicted_after_train)

tensor([0.0277, 0.9699, 0.0024])
