In [93]:
import numpy as np
import torch
import torch.nn as nn

In [94]:
input = torch.tensor([1, 3, 0]).float()
labels = torch.tensor([0, 1, 0]).float()

weights = torch.tensor([[0.1, 0.2, -0.3], [-0.6, -0.5, 2], [-0.2, 0.5, -3]]).float()
biases = torch.tensor([0.1, 0.1, 0.1]).float()

In [95]:
def feed_forward(input: torch.tensor, weights: torch.tensor, biases: torch.tensor) -> torch.tensor:
    z = torch.matmul(weights, input) + biases
    return nn.Softmax(dim=0)(z)

In [96]:
def compute_gradients(input: torch.tensor, labels: torch.tensor, predicted: torch.tensor) -> (torch.tensor, torch.tensor):
    return torch.mul(predicted - labels, input), predicted - labels

In [97]:
predicted = feed_forward(input, weights, biases)
print(predicted)

tensor([0.3469, 0.0211, 0.6320])


In [98]:
d_weights, d_biases = compute_gradients(input, labels, predicted)
print(d_weights)
print(d_biases)

tensor([ 0.3469, -2.9367,  0.0000])
tensor([ 0.3469, -0.9789,  0.6320])


In [99]:
weights = weights - d_weights
biases = biases - d_biases

In [100]:
predicted_after_train = feed_forward(input, weights, biases)
print(predicted_after_train)

tensor([0.3848, 0.0881, 0.5271])
