In [165]:
import torch
import torch.nn as nn

In [166]:
input_d = torch.tensor([1, 3, 0]).float()
labels = torch.tensor([0, 1, 0]).float()

weights = torch.tensor([[0.1, 0.2, -0.3], [-0.6, -0.5, 2], [-0.2, 0.5, -3]]).float()
biases = torch.tensor([0.1, 0.1, 0.1]).float()

In [167]:
def feed_forward(input_arg: torch.tensor, weights_arg: torch.tensor, biases_arg: torch.tensor) -> torch.tensor:
    z = torch.matmul(weights_arg, input_arg) + biases_arg
    return nn.Softmax(dim=0)(z)

In [168]:
def compute_gradients(input_arg: torch.tensor, labels_arg: torch.tensor, predicted_arg: torch.tensor) -> (torch.tensor, torch.tensor):
    return torch.matmul(input_arg.view(-1, 1), (predicted_arg - labels_arg).view(1, -1)), predicted_arg - labels_arg

In [169]:
predicted = feed_forward(input_d, weights, biases)
print(predicted)

tensor([0.3469, 0.0211, 0.6320])


In [170]:
d_weights, d_biases = compute_gradients(input_d, labels, predicted)
print(d_weights)
print(d_biases)

tensor([[ 0.3469, -0.9789,  0.6320],
        [ 1.0406, -2.9367,  1.8961],
        [ 0.0000, -0.0000,  0.0000]])
tensor([ 0.3469, -0.9789,  0.6320])


In [171]:
weights = weights - d_weights
biases = biases - d_biases

print(weights)
print(biases)

tensor([[-0.2469,  1.1789, -0.9320],
        [-1.6406,  2.4367,  0.1039],
        [-0.2000,  0.5000, -3.0000]])
tensor([-0.2469,  1.0789, -0.5320])


In [162]:
predicted_after_train = feed_forward(input_d, weights, biases)
print(predicted_after_train)

tensor([0.0239, 0.9736, 0.0025])
