<a href="https://colab.research.google.com/github/Tensor-Reloaded/Advanced-Topics-in-Neural-Networks-Template-2023/blob/main/Lab1/TensorOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorboard

# Tensor

## Tensor Creation

In [8]:
# From Python lists:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [11]:
# Random tensor with a given size
torch.rand((4, 8))

tensor([[0.7334, 0.5990, 0.5604, 0.0939, 0.1298, 0.3652, 0.7000, 0.2137],
        [0.6621, 0.9500, 0.1914, 0.8693, 0.6357, 0.3245, 0.7121, 0.6523],
        [0.2313, 0.7098, 0.7683, 0.3794, 0.7030, 0.0241, 0.7564, 0.2906],
        [0.7373, 0.9153, 0.2873, 0.3964, 0.2253, 0.2775, 0.1097, 0.0178]])

In [13]:
# Zero tensor
torch.zeros((3, 3, 3))

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [14]:
torch.arange(5, 15, 2)

tensor([ 5,  7,  9, 11, 13])

In [15]:
torch.full((2, 10), 5)

tensor([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [16]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

## Operations with Tensors

In [11]:
t1 = torch.rand((100, 20, 30))
t2 = torch.rand((100, 20, 30))
print(t1.shape, t2.shape)

torch.Size([100, 20, 30]) torch.Size([100, 20, 30])


In [15]:
print((t1 * t2).shape)
torch.equal(t1 * t2, torch.mul(t1, t2))

torch.Size([100, 20, 30])


True

In [16]:
t2t = t2.transpose(1, 2)
print(t2t.shape)
print((t1 @ t2t).shape)
torch.equal(t1 @ t2t, torch.matmul(t1, t2t))

torch.Size([100, 30, 20])
torch.Size([100, 20, 20])


True

## Casting tensors to device

In [2]:
# Tensors are by default on CPU
# Please ensure that you have access to a GPU first (in Google Colab, change Runtime type to T4 GPU).
x = torch.arange(5, 15, 2)
x_cuda = x.to('cuda')

In [4]:
x_cuda

tensor([ 5,  7,  9, 11, 13], device='cuda:0')

In [5]:
# Tensors should be on the same device
x_cuda + x

RuntimeError: ignored

In [4]:
torch.manual_seed(10)
a = torch.rand((10000, 200, 300))
b = torch.rand((10000, 200, 300))
print("a", a.shape)
print("b", b.shape)
print("b transposed", b.transpose(1, 2).shape)

a torch.Size([10000, 200, 300])
b torch.Size([10000, 200, 300])
b transposed torch.Size([10000, 300, 200])


In [5]:
%%timeit
c = (a * b) @ b.transpose(1, 2)
c.mean(axis=1)

5.63 s ± 788 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
a_cuda = a.to('cuda')
b_cuda = b.to('cuda')

In [9]:
%%timeit
# Now it is much faster
c_cuda = (a_cuda * b_cuda) @ b_cuda.transpose(1, 2)
c_cuda.mean(axis=1)

The slowest run took 4.75 times longer than the fastest. This could mean that an intermediate result is being cached.
76 µs ± 59.3 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
