In [1]:
import numpy as np
from typing import Tuple
from numpy import ndarray

from sklearn.metrics import accuracy_score

In [2]:
def softmax(x):
    return np.exp(x)/sum(np.exp(x))

In [3]:
x=np.array([1,3,0])
w=np.array([[0.3,0.1,-2],
           [-0.6,-0.5,2],
           [-1,-0.5,0.1]])
b=np.array([0.1,0.1,0.1])
y=np.array([0,1,0])
lr=0.1

In [4]:
z=w.T@x+b
y_pred=softmax(z)
grad=y_pred-y
grad_w=grad@x.T
grad_b=grad

In [5]:
w=w-lr*grad_w
b=b-lr*grad_b
print(w)
print(b)

[[ 0.59825139  0.39825139 -1.70174861]
 [-0.30174861 -0.20174861  2.29825139]
 [-0.70174861 -0.20174861  0.39825139]]
[0.09959481 0.19955219 0.000853  ]
